### ISSUE TITLE
Update all synapse workflows to use synapse cwl tools 1.0

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-workflows#22]
Use this [release](https://github.com/Sage-Bionetworks-Workflows/dockstore-tool-synapseclient/tree/v1.0)

Workflows that use the synStore tool should return the synapse id(s) of the files stored.

**Comment by andrewelamb** [comment]
@BrunoGrandePhD Could you do this for the mutation models workflow you just wrote? Essentially in the workflow you'll want the syn_store step to have the synapse id as output, and then have the workflow itself output that as well.

[This](https://github.com/CRI-iAtlas/iatlas-workflows/blob/add_driver_results_workflow/utils/subworkflows/CWL/syn_get_and_unzip_workflow.cwl) workflow has an example of a workflow having an output.

**Comment by BrunoGrandePhD** [comment]
Done! See my PR here: #23
